image: node:16-alpine

stages:
 - build
 - deploy

build_code:
 stage: build
 only:
 - main
 - testing
 tags:
 - testing
 allow_failure: true
 script:
 - echo build stage
 - npm config set registry https://registry.npm.taobao.org
 - npm install
 - npm build
 - echo build success


build_image:
 stage: build
 needs:
 - build_code
 only:
 - main
 - testing
 tags:
 - testing
 script:
 - echo build image stage

deploy:
 stage: deploy
 needs:
 - build_image
 tags:
 - testing
 only:
 - main
 - testing
 script:
 - echo deploy stage
