image: node:14-alpine

stages:
 - build
 - deploy

build_code:
 stage: build
 only:
 - main
 - testing
 tags:
 - testing
 script:
 - echo build stage
 - pnpm install
 - pnpm build
 - echo build success


build_image:
 stage: build
 needs:
 - build_code
 only:
 - main
 - testing
 tags:
 - testing
 script:
 - echo build image stage

deploy:
 stage: deploy
 needs:
 - build_image
 tags:
 - testing
 only:
 - main
 - testing
 script:
 - echo deploy stage
