stages:
 - build
 - deploy

build_code:
 stage: build
 script:
 - echo build stage

build_image:
 stage: build
 script:
 - echo build image stage 

deploy:
 stage: deploy
 script:
 - echo deploy stage